/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-11-02 13:27:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class RegistrationPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Registration Page</title>\n");
      out.write("<script type=\"text/javascript\" src=\"Script/loginScript.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction checkemail() {\n");
      out.write("\t\tvar email = document.getElementById(\"UserEmail\").value;\n");
      out.write("\t\tif (email) {\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl : \"Check\",\n");
      out.write("\t\t\t\ttype : \"post\",\n");
      out.write("\t\t\t\tdata : {\n");
      out.write("\t\t\t\t\temail : document.getElementById(\"UserEmail\").value\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tsuccess : function(response) {\n");
      out.write("\t\t\t\t\tif (response == \"{success: true}\")\n");
      out.write("\t\t\t\t\t\t$(\"#email\").html('Existing account');\n");
      out.write("\t\t\t\t\telse if (response == \"{success: false}\")\n");
      out.write("\t\t\t\t\t\t$(\"#email\").html('Account valid');\n");
      out.write("\t\t\t\t\telse\n");
      out.write("\t\t\t\t\t\t$(\"#email\").html('Account invalid');\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror : function() {\n");
      out.write("\t\t\t\t\t$(\"#email\").html('there is error while submit' + response);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\t$('#email_status').html(\"\");\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/registrationPage.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div class=\"panel panel-primary\">\n");
      out.write("\t\t<div class=\"panel-heading\">*</div>\n");
      out.write("\t\t<!-- can give button here in * -->\n");
      out.write("\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t<h2 align=\"center\">Registration Form</h2>\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<fieldset>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<form action=\"RegisterServlet\" method=\"post\" name=\"myform\"\n");
      out.write("\t\t\t\t\t\tonsubmit=\"return validateform();\">\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<label>Full Name</label> <input type=\"text\" name=\"name\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"Enter User Name\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<span id=\"name\" style=\"color: red\"></span>\n");
      out.write("\t\t\t\t\t\t");

							String nameError = (String) session.getAttribute("error1");
							//out.print(nameError);
							if (nameError != null) {
								out.print("<p style=\"color:red\"> " + nameError + "</p> <br>");
							}
							session.removeAttribute("error1");
						
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<label>Email id</label><input type=\"email\" name=\"email\"\n");
      out.write("\t\t\t\t\t\t\t\tid=\"UserEmail\" class=\"form-control\" placeholder=\"Enter EmailId\"\n");
      out.write("\t\t\t\t\t\t\t\tonkeyup=\"checkemail();\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<span id=\"email\" style=\"color: red\"></span>\n");
      out.write("\t\t\t\t\t\t");

							String emailError = (String) session.getAttribute("error2");
							if (emailError != null)
								out.print("<p style=\"color:red\"> " + emailError + " </p><br>");
							session.removeAttribute("error2");
						
      out.write("\n");
      out.write("\t\t\t\t\t\t<span id=\"email_status\"></span>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<label>PhoneNumber</label><input type=\"number\" name=\"phoneNumber\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"Enter 10 digit phone number\"\n");
      out.write("\t\t\t\t\t\t\t\trequired />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<span id=\"phoneNumber\" style=\"color: red\"></span>\n");
      out.write("\t\t\t\t\t\t");

							String phoneNumberError = (String) session.getAttribute("error3");
							if (phoneNumberError != null)
								out.print("<p style=\"color:red\">" + phoneNumberError + "</p><br>");
							session.removeAttribute("error3");
						
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<label> Password</label><input type=\"password\" name=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\trequired class=\"form-control\" placeholder=\"Enter password\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<span id=\"password\" style=\"color: red\"></span>\n");
      out.write("\t\t\t\t\t\t");

							String passwordError = (String) session.getAttribute("error4");
							if (passwordError != null)
								out.print("<p style=\"color:red\">" + passwordError + "</p><br>");
							session.removeAttribute("error4");
						
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<br> <input type=\"submit\" value=\"Register\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"index.jsp\">Already have an account</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</fieldset>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
